version: '3.8'

services:
  mysql:
    container_name: openapi-database
    build:
      dockerfile: Dockerfile
      context: ./db
    image: fkaa/openapi-database
    environment:
      - MYSQL_DATABASE=openapi_db
      - MYSQL_USER=openapi_jh
      - MYSQL_PASSWORD=openapi_jh_3323
      - MYSQL_ROOT_PASSWORD=openapi_jh_3323
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
    volumes:
      - ./db/config:/etc/mysql/conf.d
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3361:3306"
