version: '3.8'

services:
  mysql:
    container_name: mysql_local
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3361:3306"
    environment:
      - MYSQL_DATABASE=openapi_db
      - MYSQL_USER=openapi_jh
      - MYSQL_PASSWORD=openapi_jh_3323
      - MYSQL_ROOT_PASSWORD=openapi_jh_3323
      - TZ=Asia/Seoul
