DROP TABLE IF EXISTS `english_word`;

-- auto-generated definition
create table `english_word`
(
    `idx`               int auto_increment                                   comment '식별번호',
    `vocabulary`        varchar(100)                                         not null comment '단어',
    `meaning`           varchar(100)                                         not null comment '뜻',
    `level`             enum ('ELEMENT', 'MIDDLE', 'HIGH') default 'ELEMENT' not null comment '난이도',
    `reg_datetime`      datetime                                             null comment '등록일',
    `reg_user_nickname` varchar(100)                       default '1'       not null comment '등록자 idx',
    `mod_datetime`      datetime                                             null comment '수정일자',
    `mod_user_nickname` varchar(100)                                         null comment '수정자 idx',
    PRIMARY KEY (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

LOCK TABLES `english_word` WRITE;

INSERT INTO `english_word`
VALUES (1, 'aunt', '이모, 고모', 'ELEMENT', NOW(), '관리자', null, null),
       (2, 'grandfather', '할아버지', 'ELEMENT', NOW(), '관리자', null, null),
       (3, 'grandmother', '할머니', 'ELEMENT', NOW(), '관리자', null, null),
       (4, 'bookstore', '서점', 'ELEMENT', NOW(), '관리자', null, null),
       (5, 'building', '건물, 건축', 'ELEMENT', NOW(), '관리자', null, null),
       (6, 'corner', '구석, 모퉁이', 'ELEMENT', NOW(), '관리자', null, null),
       (7, 'office', '사무실, 회사', 'ELEMENT', NOW(), '관리자', null, null),
       (8, 'post', '우편', 'ELEMENT', NOW(), '관리자', null, null),
       (9, 'restaurant', '식당, 레스토랑', 'ELEMENT', NOW(), '관리자', null, null),
       (10, 'watermelon', '수박', 'ELEMENT', NOW(), '관리자', null, null),
       (11, 'than', '~보다는', 'ELEMENT', NOW(), '관리자', null, null),
       (12, 'feel', '느끼다, 감정', 'ELEMENT', NOW(), '관리자', null, null),
       (13, 'change', '변하다, 바꾸다', 'ELEMENT', NOW(), '관리자', null, null),
       (14, 'show', '보여주다, 쇼', 'ELEMENT', NOW(), '관리자', null, null),
       (15, 'hope', '희망하다, 바라다', 'ELEMENT', NOW(), '관리자', null, null),
       (16, 'invite', '초대하다', 'ELEMENT', NOW(), '관리자', null, null),
       (17, 'drink', '마시다', 'ELEMENT', NOW(), '관리자', null, null),
       (18, 'work', '일하다, 작업', 'ELEMENT', NOW(), '관리자', null, null),
       (19, 'read', '읽다', 'ELEMENT', NOW(), '관리자', null, null),
       (20, 'ride', '타다', 'ELEMENT', NOW(), '관리자', null, null),
       (21, 'talk', '말하다', 'ELEMENT', NOW(), '관리자', null, null),
       (22, 'hold', '잡다', 'ELEMENT', NOW(), '관리자', null, null),
       (23, 'because', '왜냐하면, ~때문에', 'ELEMENT', NOW(), '관리자', null, null),
       (24, 'fall', '가을, 떨어지다', 'ELEMENT', NOW(), '관리자', null, null),
       (25, 'move', '움직이다, 이동하다', 'ELEMENT', NOW(), '관리자', null, null),
       (26, 'paint', '그리다, 칠하다, 페인트', 'ELEMENT', NOW(), '관리자', null, null),
       (27, 'season', '계절, 시기, 시즌', 'ELEMENT', NOW(), '관리자', null, null),
       (28, 'pass', '지나가다, 통과하다', 'ELEMENT', NOW(), '관리자', null, null),
       (29, 'worry', '걱정하다, 우려하다', 'ELEMENT', NOW(), '관리자', null, null),
       (30, 'spring', '봄, 스프링', 'ELEMENT', NOW(), '관리자', null, null),
       (31, 'summer', '여름', 'ELEMENT', NOW(), '관리자', null, null),
       (32, 'eat', '먹다', 'ELEMENT', NOW(), '관리자', null, null),
       (33, 'write', '쓰다', 'ELEMENT', NOW(), '관리자', null, null),
       (34, 'winter', '겨울', 'ELEMENT', NOW(), '관리자', null, null),
       (35, 'mouse', '쥐', 'ELEMENT', NOW(), '관리자', null, null),
       (36, 'sleep', '자다, 잠', 'ELEMENT', NOW(), '관리자', null, null),
       (37, 'see', '보다', 'ELEMENT', NOW(), '관리자', null, null),
       (38, 'rabbit', '토끼', 'ELEMENT', NOW(), '관리자', null, null),
       (39, 'snake', '뱀', 'ELEMENT', NOW(), '관리자', null, null),
       (40, 'toy', '장난감', 'ELEMENT', NOW(), '관리자', null, null),
       (41, 'concert', '공연, 콘서트', 'ELEMENT', NOW(), '관리자', null, null),
       (42, 'trip', '여행', 'ELEMENT', NOW(), '관리자', null, null),
       (43, 'course', '과정, 코스', 'ELEMENT', NOW(), '관리자', null, null),
       (44, 'guitar', '기타', 'ELEMENT', NOW(), '관리자', null, null),
       (45, 'musical', '음악의, 뮤지컬의', 'ELEMENT', NOW(), '관리자', null, null),
       (46, 'bucket', '양동이', 'ELEMENT', NOW(), '관리자', null, null),
       (47, 'model', '모델, 모형, 방법', 'ELEMENT', NOW(), '관리자', null, null),
       (48, 'congratulation', '축하, 축하하다', 'ELEMENT', NOW(), '관리자', null, null),
       (49, 'date', '날짜', 'ELEMENT', NOW(), '관리자', null, null),
       (50, 'tomorrow', '내일', 'ELEMENT', NOW(), '관리자', null, null),
       (51, 'soon', '곧, 조만간, 금방', 'ELEMENT', NOW(), '관리자', null, null),
       (52, 'already', '이미, 벌써', 'ELEMENT', NOW(), '관리자', null, null),
       (53, 'yet', '아직', 'ELEMENT', NOW(), '관리자', null, null),
       (54, 'earache', '귀앓이, 귀아픔', 'ELEMENT', NOW(), '관리자', null, null),
       (55, 'stomachache', '복통, 배탈', 'ELEMENT', NOW(), '관리자', null, null),
       (56, 'car', '자동차', 'ELEMENT', NOW(), '관리자', null, null),
       (57, 'helicopter', '헬리콥터, 헬기', 'ELEMENT', NOW(), '관리자', null, null),
       (58, 'airplane', '비행기', 'ELEMENT', NOW(), '관리자', null, null),
       (59, 'behind', '~뒤에, 숨겨진', 'ELEMENT', NOW(), '관리자', null, null),
       (60, 'between', '~사이에', 'ELEMENT', NOW(), '관리자', null, null),
       (61, 'near', '근처에, 가깝게', 'ELEMENT', NOW(), '관리자', null, null),
       (62, 'street', '거리, 길', 'ELEMENT', NOW(), '관리자', null, null),
       (63, 'away', '떨어져, 떠나', 'ELEMENT', NOW(), '관리자', null, null),
       (64, 'food', '음식', 'ELEMENT', NOW(), '관리자', null, null),
       (65, 'water', '물', 'ELEMENT', NOW(), '관리자', null, null),
       (66, 'when', '언제', 'ELEMENT', NOW(), '관리자', null, null),
       (67, 'why', '왜', 'ELEMENT', NOW(), '관리자', null, null),
       (68, 'leaf', '나뭇잎', 'ELEMENT', NOW(), '관리자', null, null),
       (69, 'may', '~일지도 모른다', 'ELEMENT', NOW(), '관리자', null, null),
       (70, 'will', '~할 것이다', 'ELEMENT', NOW(), '관리자', null, null),
       (71, 'doctor', '의사, 박사', 'ELEMENT', NOW(), '관리자', null, null),
       (72, 'nurse', '간호사', 'ELEMENT', NOW(), '관리자', null, null),
       (73, 'driver', '운전사, 기사', 'ELEMENT', NOW(), '관리자', null, null),
       (74, 'pilot', '조종사, 비행사', 'ELEMENT', NOW(), '관리자', null, null),
       (75, 'policeofficer', '경찰관', 'ELEMENT', NOW(), '관리자', null, null),
       (76, 'singer', '가수', 'ELEMENT', NOW(), '관리자', null, null),
       (77, 'floor', '바닥, 층', 'ELEMENT', NOW(), '관리자', null, null),
       (78, 'present', '선물, 현재의', 'ELEMENT', NOW(), '관리자', null, null),
       (79, 'elementary', '초보의, 기초의, 기본의', 'ELEMENT', NOW(), '관리자', null, null),
       (80, 'last', '지난, 마지막의', 'ELEMENT', NOW(), '관리자', null, null),
       (81, 'lucky', '운이 좋은, 행운의', 'ELEMENT', NOW(), '관리자', null, null),
       (82, 'expensive', '비싼', 'ELEMENT', NOW(), '관리자', null, null),
       (83, 'delicious', '맛있는, 맛좋은', 'ELEMENT', NOW(), '관리자', null, null),
       (84, 'same', '똑같은, 같은', 'ELEMENT', NOW(), '관리자', null, null),
       (85, 'cool', '시원한, 냉각', 'ELEMENT', NOW(), '관리자', null, null),
       (86, 'warm', '따뜻한, 온난한', 'ELEMENT', NOW(), '관리자', null, null),
       (87, 'little', '작은, 조금, 약간의', 'ELEMENT', NOW(), '관리자', null, null),
       (88, 'fast', '빠른, 빨리, 단식하다', 'ELEMENT', NOW(), '관리자', null, null),
       (89, 'surprise', '놀라다, 깜짝', 'ELEMENT', NOW(), '관리자', null, null),
       (90, 'heavy', '무거운', 'ELEMENT', NOW(), '관리자', null, null),
       (91, 'able', '~할 수 있는, 유능한', 'ELEMENT', NOW(), '관리자', null, null),
       (92, 'agree', '동의하다, 승낙하다', 'ELEMENT', NOW(), '관리자', null, null),
       (93, 'enough', '충분히', 'ELEMENT', NOW(), '관리자', null, null),
       (94, 'introduce', '소개하다, 도입하다', 'ELEMENT', NOW(), '관리자', null, null),
       (95, 'popular', '인기 있는, 유명한', 'ELEMENT', NOW(), '관리자', null, null),
       (96, 'army', '군대', 'ELEMENT', NOW(), '관리자', null, null),
       (97, 'death', '죽음, 사망', 'ELEMENT', NOW(), '관리자', null, null),
       (98, 'spend', '쓰다, 보내다, 사용하다', 'ELEMENT', NOW(), '관리자', null, null),
       (99, 'subject', '과목, 주제, 대상', 'ELEMENT', NOW(), '관리자', null, null),
       (100, 'exercise', '운동, 연습, 훈련', 'ELEMENT', NOW(), '관리자', null, null),
       (101, 'excuse', '변명, 핑계', 'ELEMENT', NOW(), '관리자', null, null),
       (102, 'share', '공유하다, 나누다', 'ELEMENT', NOW(), '관리자', null, null),
       (103, 'pick', '고르다, 선택하다, 뽑다', 'ELEMENT', NOW(), '관리자', null, null),
       (104, 'habit', '습관, 버릇', 'ELEMENT', NOW(), '관리자', null, null),
       (105, 'health', '건강', 'ELEMENT', NOW(), '관리자', null, null),
       (106, 'possible', '가능한, 할 수 있는', 'ELEMENT', NOW(), '관리자', null, null),
       (107, 'check', '확인하다, 점검하다', 'ELEMENT', NOW(), '관리자', null, null),
       (108, 'follow', '따르다, 뒤를 잇다', 'ELEMENT', NOW(), '관리자', null, null),
       (109, 'south', '남쪽', 'ELEMENT', NOW(), '관리자', null, null),
       (110, 'north', '북쪽', 'ELEMENT', NOW(), '관리자', null, null),
       (111, 'social', '사회의, 사교적인', 'ELEMENT', NOW(), '관리자', null, null),
       (112, 'someone', '누군가', 'ELEMENT', NOW(), '관리자', null, null),
       (113, 'useful', '유용한, 쓸모 있는', 'ELEMENT', NOW(), '관리자', null, null),
       (114, 'war', '전쟁', 'ELEMENT', NOW(), '관리자', null, null),
       (115, 'factory', '공장', 'ELEMENT', NOW(), '관리자', null, null),
       (116, 'result', '결과', 'ELEMENT', NOW(), '관리자', null, null),
       (117, 'shape', '형태, 모양', 'ELEMENT', NOW(), '관리자', null, null),
       (118, 'daily', '매일의, 일상적인', 'ELEMENT', NOW(), '관리자', null, null),
       (119, 'allow', '허락하다', 'ELEMENT', NOW(), '관리자', null, null),
       (120, 'image', '이미지, 영상, 그림', 'ELEMENT', NOW(), '관리자', null, null),
       (121, 'mistake', '실수, 잘못', 'ELEMENT', NOW(), '관리자', null, null),
       (122, 'national', '국가의, 전국민의', 'ELEMENT', NOW(), '관리자', null, null),
       (123, 'nobody', '아무도 ~ 않다', 'ELEMENT', NOW(), '관리자', null, null),
       (124, 'crowd', '군중, 붐비다', 'ELEMENT', NOW(), '관리자', null, null),
       (125, 'raise', '올리다, 높이다', 'ELEMENT', NOW(), '관리자', null, null),
       (126, 'serve', '제공하다, 봉사하다', 'ELEMENT', NOW(), '관리자', null, null),
       (127, 'success', '성공', 'ELEMENT', NOW(), '관리자', null, null),
       (128, 'improve', '개선하다, 향상하다', 'ELEMENT', NOW(), '관리자', null, null),
       (129, 'accept', '받아들이다, 인정하다', 'ELEMENT', NOW(), '관리자', null, null),
       (130, 'appear', '나타나다', 'ELEMENT', NOW(), '관리자', null, null),
       (131, 'product', '상품, 제품, 생산하다', 'ELEMENT', NOW(), '관리자', null, null),
       (132, 'express', '표현하다, 나타내다', 'ELEMENT', NOW(), '관리자', null, null),
       (133, 'forever', '영원히, 항상, 계속', 'ELEMENT', NOW(), '관리자', null, null),
       (134, 'law', '법, 법률', 'ELEMENT', NOW(), '관리자', null, null),
       (135, 'natural', '자연의, 천연의', 'ELEMENT', NOW(), '관리자', null, null),
       (136, 'poem', '시', 'ELEMENT', NOW(), '관리자', null, null),
       (137, 'notice', '알아차리다, 게시판', 'ELEMENT', NOW(), '관리자', null, null),
       (138, 'suggest', '제안하다, 제의하다', 'ELEMENT', NOW(), '관리자', null, null),
       (139, 'disease', '질병, 병', 'ELEMENT', NOW(), '관리자', null, null),
       (140, 'soldier', '군인, 병사', 'ELEMENT', NOW(), '관리자', null, null),
       (141, 'sudden', '갑작스러운, 느닷없이', 'ELEMENT', NOW(), '관리자', null, null),
       (142, 'provide', '제공하다, 공급하다', 'ELEMENT', NOW(), '관리자', null, null),
       (143, 'support', '지원하다, 지지하다', 'ELEMENT', NOW(), '관리자', null, null),
       (144, 'average', '평균, 보통의', 'ELEMENT', NOW(), '관리자', null, null),
       (145, 'deliver', '배달하다, 전달하다', 'ELEMENT', NOW(), '관리자', null, null),
       (146, 'remain', '남다, 머무르다', 'ELEMENT', NOW(), '관리자', null, null),
       (147, 'regular', '규칙적인, 정기적인', 'ELEMENT', NOW(), '관리자', null, null),
       (148, 'difficulty', '어려움, 곤경', 'ELEMENT', NOW(), '관리자', null, null),
       (149, 'purpose', '목적, 목표', 'ELEMENT', NOW(), '관리자', null, null),
       (150, 'experiment', '실험, 시도', 'ELEMENT', NOW(), '관리자', null, null);

UNLOCK TABLES;
