spring:
  profiles:
    active: local
    group:
      local: local-config, local-db
      prod: prod-config, prod-db
  mvc:
    throw-exception-if-no-handler-found: true

naver:
  open-api:
    client:
      id:
        key: X-Naver-Client-Id
        value: GjRXRWmJva6Aiy69soqw
      pw:
        key: X-Naver-Client-Secret
        value: B7rBBcamM2
    dictionary:
      path: https://openapi.naver.com/v1/search/encyc.json
      method: GET
