spring:
  profiles:
    active: local
    group:
      local: local-config, local-db
      prod: prod-config, prod-db
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  file:
    name: ./logs/app.log
    path: ./logs/
  logback:
    rollingpolicy:
      max-history: 3
      max-file-size: 100MB

naver:
  open-api:
    client:
      id:
        key: X-Naver-Client-Id
        value: GjRXRWmJva6Aiy69soqw
      pw:
        key: X-Naver-Client-Secret
        value: B7rBBcamM2
    dictionary:
      path: https://openapi.naver.com/v1/search/encyc.json
      method: GET
