INSERT INTO openapi_db.user (id, password, nick_name, email)
VALUES('admin', CONCAT('*', UPPER(SHA1(UNHEX(SHA1('openapi_jihyeon'))))), '관리자', 'wlgus120332@gmail.com');

INSERT INTO openapi_db.english_word (vocabulary, meaning, level, reg_datetime, reg_user_idx)
VALUES ('aunt', '이모, 고모', 'ELEMENT', NOW(), 1),
       ('grandfather', '할아버지', 'ELEMENT', NOW(), 1),
       ('grandmother', '할머니', 'ELEMENT', NOW(), 1),
       ('bookstore', '서점', 'ELEMENT', NOW(), 1),
       ('building', '건물, 건축', 'ELEMENT', NOW(), 1),
       ('corner', '구석, 모퉁이', 'ELEMENT', NOW(), 1),
       ('office', '사무실, 회사', 'ELEMENT', NOW(), 1),
       ('post', '우편', 'ELEMENT', NOW(), 1),
       ('restaurant', '식당, 레스토랑', 'ELEMENT', NOW(), 1),
       ('watermelon', '수박', 'ELEMENT', NOW(), 1),
       ('than', '~보다는', 'ELEMENT', NOW(), 1),
       ('feel', '느끼다, 감정', 'ELEMENT', NOW(), 1),
       ('change', '변하다, 바꾸다', 'ELEMENT', NOW(), 1),
       ('show', '보여주다, 쇼', 'ELEMENT', NOW(), 1),
       ('hope', '희망하다, 바라다', 'ELEMENT', NOW(), 1),
       ('invite', '초대하다', 'ELEMENT', NOW(), 1),
       ('drink', '마시다', 'ELEMENT', NOW(), 1),
       ('work', '일하다, 작업', 'ELEMENT', NOW(), 1),
       ('read', '읽다', 'ELEMENT', NOW(), 1),
       ('ride', '타다', 'ELEMENT', NOW(), 1),
       ('talk', '말하다', 'ELEMENT', NOW(), 1),
       ('hold', '잡다', 'ELEMENT', NOW(), 1),
       ('because', '왜냐하면, ~때문에', 'ELEMENT', NOW(), 1),
       ('fall', '가을, 떨어지다', 'ELEMENT', NOW(), 1),
       ('move', '움직이다, 이동하다', 'ELEMENT', NOW(), 1),
       ('paint', '그리다, 칠하다, 페인트', 'ELEMENT', NOW(), 1),
       ('season', '계절, 시기, 시즌', 'ELEMENT', NOW(), 1),
       ('pass', '지나가다, 통과하다', 'ELEMENT', NOW(), 1),
       ('worry', '걱정하다, 우려하다', 'ELEMENT', NOW(), 1),
       ('spring', '봄, 스프링', 'ELEMENT', NOW(), 1),
       ('summer', '여름', 'ELEMENT', NOW(), 1),
       ('eat', '먹다', 'ELEMENT', NOW(), 1),
       ('write', '쓰다', 'ELEMENT', NOW(), 1),
       ('winter', '겨울', 'ELEMENT', NOW(), 1),
       ('mouse', '쥐', 'ELEMENT', NOW(), 1),
       ('sleep', '자다, 잠', 'ELEMENT', NOW(), 1),
       ('see', '보다', 'ELEMENT', NOW(), 1),
       ('rabbit', '토끼', 'ELEMENT', NOW(), 1),
       ('snake', '뱀', 'ELEMENT', NOW(), 1),
       ('toy', '장난감', 'ELEMENT', NOW(), 1),
       ('concert', '공연, 콘서트', 'ELEMENT', NOW(), 1),
       ('trip', '여행', 'ELEMENT', NOW(), 1),
       ('course', '과정, 코스', 'ELEMENT', NOW(), 1),
       ('guitar', '기타', 'ELEMENT', NOW(), 1),
       ('musical', '음악의, 뮤지컬의', 'ELEMENT', NOW(), 1),
       ('bucket', '양동이', 'ELEMENT', NOW(), 1),
       ('model', '모델, 모형, 방법', 'ELEMENT', NOW(), 1),
       ('congratulation', '축하, 축하하다', 'ELEMENT', NOW(), 1),
       ('date', '날짜', 'ELEMENT', NOW(), 1),
       ('tomorrow', '내일', 'ELEMENT', NOW(), 1),
       ('soon', '곧, 조만간, 금방', 'ELEMENT', NOW(), 1),
       ('already', '이미, 벌써', 'ELEMENT', NOW(), 1),
       ('yet', '아직', 'ELEMENT', NOW(), 1),
       ('earache', '귀앓이, 귀아픔', 'ELEMENT', NOW(), 1),
       ('stomachache', '복통, 배탈', 'ELEMENT', NOW(), 1),
       ('car', '자동차', 'ELEMENT', NOW(), 1),
       ('helicopter', '헬리콥터, 헬기', 'ELEMENT', NOW(), 1),
       ('airplane', '비행기', 'ELEMENT', NOW(), 1),
       ('behind', '~뒤에, 숨겨진', 'ELEMENT', NOW(), 1),
       ('between', '~사이에', 'ELEMENT', NOW(), 1),
       ('near', '근처에, 가깝게', 'ELEMENT', NOW(), 1),
       ('street', '거리, 길', 'ELEMENT', NOW(), 1),
       ('away', '떨어져, 떠나', 'ELEMENT', NOW(), 1),
       ('food', '음식', 'ELEMENT', NOW(), 1),
       ('water', '물', 'ELEMENT', NOW(), 1),
       ('when', '언제', 'ELEMENT', NOW(), 1),
       ('why', '왜', 'ELEMENT', NOW(), 1),
       ('leaf', '나뭇잎', 'ELEMENT', NOW(), 1),
       ('may', '~일지도 모른다', 'ELEMENT', NOW(), 1),
       ('will', '~할 것이다', 'ELEMENT', NOW(), 1),
       ('doctor', '의사, 박사', 'ELEMENT', NOW(), 1),
       ('nurse', '간호사', 'ELEMENT', NOW(), 1),
       ('driver', '운전사, 기사', 'ELEMENT', NOW(), 1),
       ('pilot', '조종사, 비행사', 'ELEMENT', NOW(), 1),
       ('policeofficer', '경찰관', 'ELEMENT', NOW(), 1),
       ('singer', '가수', 'ELEMENT', NOW(), 1),
       ('floor', '바닥, 층', 'ELEMENT', NOW(), 1),
       ('present', '선물, 현재의', 'ELEMENT', NOW(), 1),
       ('elementary', '초보의, 기초의, 기본의', 'ELEMENT', NOW(), 1),
       ('last', '지난, 마지막의', 'ELEMENT', NOW(), 1),
       ('lucky', '운이 좋은, 행운의', 'ELEMENT', NOW(), 1),
       ('expensive', '비싼', 'ELEMENT', NOW(), 1),
       ('delicious', '맛있는, 맛좋은', 'ELEMENT', NOW(), 1),
       ('same', '똑같은, 같은', 'ELEMENT', NOW(), 1),
       ('cool', '시원한, 냉각', 'ELEMENT', NOW(), 1),
       ('warm', '따뜻한, 온난한', 'ELEMENT', NOW(), 1),
       ('little', '작은, 조금, 약간의', 'ELEMENT', NOW(), 1),
       ('fast', '빠른, 빨리, 단식하다', 'ELEMENT', NOW(), 1),
       ('surprise', '놀라다, 깜짝', 'ELEMENT', NOW(), 1),
       ('heavy', '무거운', 'ELEMENT', NOW(), 1),
       ('able', '~할 수 있는, 유능한', 'ELEMENT', NOW(), 1),
       ('agree', '동의하다, 승낙하다', 'ELEMENT', NOW(), 1),
       ('enough', '충분히', 'ELEMENT', NOW(), 1),
       ('introduce', '소개하다, 도입하다', 'ELEMENT', NOW(), 1),
       ('popular', '인기 있는, 유명한', 'ELEMENT', NOW(), 1),
       ('army', '군대', 'ELEMENT', NOW(), 1),
       ('death', '죽음, 사망', 'ELEMENT', NOW(), 1),
       ('spend', '쓰다, 보내다, 사용하다', 'ELEMENT', NOW(), 1),
       ('subject', '과목, 주제, 대상', 'ELEMENT', NOW(), 1),
       ('exercise', '운동, 연습, 훈련', 'ELEMENT', NOW(), 1),
       ('excuse', '변명, 핑계', 'ELEMENT', NOW(), 1),
       ('share', '공유하다, 나누다', 'ELEMENT', NOW(), 1),
       ('pick', '고르다, 선택하다, 뽑다', 'ELEMENT', NOW(), 1),
       ('habit', '습관, 버릇', 'ELEMENT', NOW(), 1),
       ('health', '건강', 'ELEMENT', NOW(), 1),
       ('possible', '가능한, 할 수 있는', 'ELEMENT', NOW(), 1),
       ('check', '확인하다, 점검하다', 'ELEMENT', NOW(), 1),
       ('follow', '따르다, 뒤를 잇다', 'ELEMENT', NOW(), 1),
       ('south', '남쪽', 'ELEMENT', NOW(), 1),
       ('north', '북쪽', 'ELEMENT', NOW(), 1),
       ('social', '사회의, 사교적인', 'ELEMENT', NOW(), 1),
       ('someone', '누군가', 'ELEMENT', NOW(), 1),
       ('useful', '유용한, 쓸모 있는', 'ELEMENT', NOW(), 1),
       ('war', '전쟁', 'ELEMENT', NOW(), 1),
       ('factory', '공장', 'ELEMENT', NOW(), 1),
       ('result', '결과', 'ELEMENT', NOW(), 1),
       ('shape', '형태, 모양', 'ELEMENT', NOW(), 1),
       ('daily', '매일의, 일상적인', 'ELEMENT', NOW(), 1),
       ('allow', '허락하다', 'ELEMENT', NOW(), 1),
       ('image', '이미지, 영상, 그림', 'ELEMENT', NOW(), 1),
       ('mistake', '실수, 잘못', 'ELEMENT', NOW(), 1),
       ('national', '국가의, 전국민의', 'ELEMENT', NOW(), 1),
       ('nobody', '아무도 ~ 않다', 'ELEMENT', NOW(), 1),
       ('crowd', '군중, 붐비다', 'ELEMENT', NOW(), 1),
       ('raise', '올리다, 높이다', 'ELEMENT', NOW(), 1),
       ('serve', '제공하다, 봉사하다', 'ELEMENT', NOW(), 1),
       ('success', '성공', 'ELEMENT', NOW(), 1),
       ('improve', '개선하다, 향상하다', 'ELEMENT', NOW(), 1),
       ('accept', '받아들이다, 인정하다', 'ELEMENT', NOW(), 1),
       ('appear', '나타나다', 'ELEMENT', NOW(), 1),
       ('product', '상품, 제품, 생산하다', 'ELEMENT', NOW(), 1),
       ('express', '표현하다, 나타내다', 'ELEMENT', NOW(), 1),
       ('forever', '영원히, 항상, 계속', 'ELEMENT', NOW(), 1),
       ('law', '법, 법률', 'ELEMENT', NOW(), 1),
       ('natural', '자연의, 천연의', 'ELEMENT', NOW(), 1),
       ('poem', '시', 'ELEMENT', NOW(), 1),
       ('notice', '알아차리다, 게시판', 'ELEMENT', NOW(), 1),
       ('suggest', '제안하다, 제의하다', 'ELEMENT', NOW(), 1),
       ('disease', '질병, 병', 'ELEMENT', NOW(), 1),
       ('soldier', '군인, 병사', 'ELEMENT', NOW(), 1),
       ('sudden', '갑작스러운, 느닷없이', 'ELEMENT', NOW(), 1),
       ('provide', '제공하다, 공급하다', 'ELEMENT', NOW(), 1),
       ('support', '지원하다, 지지하다', 'ELEMENT', NOW(), 1),
       ('average', '평균, 보통의', 'ELEMENT', NOW(), 1),
       ('deliver', '배달하다, 전달하다', 'ELEMENT', NOW(), 1),
       ('remain', '남다, 머무르다', 'ELEMENT', NOW(), 1),
       ('regular', '규칙적인, 정기적인', 'ELEMENT', NOW(), 1),
       ('difficulty', '어려움, 곤경', 'ELEMENT', NOW(), 1),
       ('purpose', '목적, 목표', 'ELEMENT', NOW(), 1),
       ('experiment', '실험, 시도', 'ELEMENT', NOW(), 1)
;